// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZOUBy-Ch-WY1d1r6pm6e40y1SfREtGfU',
    appId: '1:1083555634416:web:a320629e64078d0f213635',
    messagingSenderId: '1083555634416',
    projectId: 'expense-tracker-f056b',
    authDomain: 'expense-tracker-f056b.firebaseapp.com',
    storageBucket: 'expense-tracker-f056b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaFBgPcoSW1_h3ff4Rcu7W399VzaHbH7o',
    appId: '1:1083555634416:android:7ebd063bbbc90521213635',
    messagingSenderId: '1083555634416',
    projectId: 'expense-tracker-f056b',
    storageBucket: 'expense-tracker-f056b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfW-6YWpsSf2THs9t_QSC9ZrKPU426AKY',
    appId: '1:1083555634416:ios:da0c3907701e93c0213635',
    messagingSenderId: '1083555634416',
    projectId: 'expense-tracker-f056b',
    storageBucket: 'expense-tracker-f056b.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfW-6YWpsSf2THs9t_QSC9ZrKPU426AKY',
    appId: '1:1083555634416:ios:da0c3907701e93c0213635',
    messagingSenderId: '1083555634416',
    projectId: 'expense-tracker-f056b',
    storageBucket: 'expense-tracker-f056b.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZOUBy-Ch-WY1d1r6pm6e40y1SfREtGfU',
    appId: '1:1083555634416:web:112073369f69f5a4213635',
    messagingSenderId: '1083555634416',
    projectId: 'expense-tracker-f056b',
    authDomain: 'expense-tracker-f056b.firebaseapp.com',
    storageBucket: 'expense-tracker-f056b.firebasestorage.app',
  );
}
