import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';

<<<<<<< HEAD
// ✅ Required for localization
import 'package:flutter_localizations/flutter_localizations.dart';
import 'l10n/app_localizations.dart'; // ✅ generated by flutter gen-l10n

=======
>>>>>>> 0f10098 (Your commit message)
import 'firebase_options.dart';

// Services
import 'services/auth_service.dart';

// Theme
import 'theme/theme_provider.dart';

<<<<<<< HEAD
// Providers
import 'provider/transaction_provider.dart';
import 'provider/analytic_provider.dart';
import 'provider/currency_provider.dart';
import 'provider/locale_provider.dart';

=======
>>>>>>> 0f10098 (Your commit message)
// Screens
import 'screens/auth/login_screen.dart';
import 'screens/auth/signup_screen.dart';
import 'screens/splash/splash_screen.dart';
import 'screens/dashboard/dashboard_screen.dart';
import 'screens/setting/setting.dart';
import 'screens/setting/profile_edit_screen.dart';
import 'screens/budget/advanced_budget_screen.dart';
import 'screens/analytics/analytics_screen.dart';
import 'screens/add_transaction/add_expense_screen.dart';
import 'screens/pdf/pdf.dart';

<<<<<<< HEAD
// ✅ App lock gate
import 'screens/setting/app_lock_and_permissions.dart';

=======
>>>>>>> 0f10098 (Your commit message)
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // 🔥 Initialize Firebase ONCE before app start
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const RootApp());
}

class RootApp extends StatelessWidget {
  const RootApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
<<<<<<< HEAD
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
        ChangeNotifierProvider(create: (_) => CurrencyProvider()),
        ChangeNotifierProvider(create: (_) => LocaleProvider()),

        Provider<AuthService>(create: (_) => AuthService()),

        ChangeNotifierProvider(create: (_) => TransactionProvider()),
        ChangeNotifierProvider(create: (_) => AnalyticProvider()),
=======
        // 🔥 Theme provider (ChangeNotifier)
        ChangeNotifierProvider(
          create: (_) => ThemeProvider(),
        ),

        // 🔥 Auth service (Singleton-like)
        Provider<AuthService>(
          create: (_) => AuthService(),
          lazy: true, // load only when needed
        ),
>>>>>>> 0f10098 (Your commit message)
      ],
      child: const MyApp(),
    );
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
<<<<<<< HEAD
    final themeMode =
        context.select<ThemeProvider, ThemeMode>((p) => p.themeMode);

    // ✅ Watch locale changes (updates whole app)
    final locale = context.select<LocaleProvider, Locale>((p) => p.locale);

    const supported = [
      Locale('en'),
      Locale('ur'),
      Locale('es'),
      Locale('hi'),
      Locale('ar'),
    ];
=======
    // 🔥 Only listen to theme changes
    final themeMode =
        context.select<ThemeProvider, ThemeMode>((p) => p.themeMode);
>>>>>>> 0f10098 (Your commit message)

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: "Expense Tracker",

<<<<<<< HEAD
      // ✅ Localization
      locale: locale,
      supportedLocales: supported,
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],

      // ✅ If localeProvider.locale is not set or not supported, use device locale if possible.
      // Otherwise fallback to English.
      localeResolutionCallback: (deviceLocale, supportedLocales) {
        if (deviceLocale == null) return const Locale('en');

        for (final s in supportedLocales) {
          if (s.languageCode == deviceLocale.languageCode) {
            return s;
          }
        }
        return const Locale('en');
      },

=======
>>>>>>> 0f10098 (Your commit message)
      themeMode: themeMode,
      theme: ThemeData.light(useMaterial3: true),
      darkTheme: ThemeData.dark(useMaterial3: true),

      initialRoute: "/splash",
      routes: {
        "/splash": (_) => const SplashScreen(),
        "/login": (_) => const LoginScreen(),
        "/signup": (_) => const SignupScreen(),

        "/dashboard": (_) => AppLockAndPermissionsGate(
              lockOnStart: true,
              enabled: true,
              lockAfter: const Duration(seconds: 10),
              cancelRouteName: "/settings",
              child: const DashboardScreen(),
            ),

        "/settings": (_) => const SettingsScreen(),
        "/profile_edit": (_) => const ProfileEditScreen(),
        "/advanced_budget": (_) => const AdvancedBudgetScreen(),
        "/analytics": (_) => const AnalyticsScreen(),
        "/expense": (_) => const AddExpenseScreen(),
        "/pdf": (_) => const PdfGenerateScreen(),
      },
    );
  }
}
